# Generated by Django 3.1.1 on 2020-10-02 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holamundo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cedula', models.IntegerField(default=10)),
                ('Telf', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=50)),
                ('Nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holamundo.carrera')),
            ],
        ),
    ]
