# Generated by Django 3.1.1 on 2020-10-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holamundo', '0002_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='Nombre',
            field=models.CharField(max_length=50),
        ),
    ]
