# Generated by Django 3.1.1 on 2020-10-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holamundo', '0003_auto_20201002_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Cedula', models.IntegerField(default=10)),
                ('Telf', models.CharField(max_length=50)),
                ('Edad', models.CharField(max_length=50)),
            ],
        ),
    ]
